#! /bin/sh

# Copyright (c) 2010 GhostHunter
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of copyright holders nor the names of its
#    contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL COPYRIGHT HOLDERS OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

TC_BIN="/usr/bin/truecrypt"
TC_VOLUME="/my/volume.tc"
TC_MOUNT_POINT="/home/foo"
TC_KEY=""

case "$1" in
  start)
	$TC_BIN -t -l $TC_VOLUME 2> /dev/null > /dev/null
	if [ ! $? -eq 0 ]; then
		echo  "Mounting Volume $TC_VOLUME"
		
		$TC_BIN -t --mount --protect-hidden=no  -k "$TC_KEY" $TC_VOLUME $TC_MOUNT_POINT

		if [ ! $? -eq 0 ]; then
			echo "Error mounting Volume $TC_VOLUME"
		else
			/usr/bin/logger -t truecrypt "$TC_VOLUME mounted"
			echo "Done"
		fi
	else
		echo "Volume $TC_VOLUME already mounted"
	fi
	;;
  stop)

	$TC_BIN -t -l $TC_VOLUME 2> /dev/null > /dev/null
	if [  $? -eq 0 ]; then
		echo -n "Dismounting Volume $TC_VOLUME "
		
		$TC_BIN -t -d $TC_VOLUME

		if [ ! $? -eq 0 ]; then
			echo "Error dismounting Volume $TC_VOLUME"
		else
			/usr/bin/logger -t truecrypt "$TC_VOLUME dismounted"
			echo "Done"
		fi
	else
		echo "Volume $TC_VOLUME not mounted"
	
	fi
	;;
  status)
	$TC_BIN -t -l $TC_VOLUME 2> /dev/null > /dev/null
	if [  $? -eq 0 ]; then
		echo "$TC_VOLUME is mounted"
	else
		echo "$TC_VOLUME is not mounted"
	fi
	;;
  *)
	echo "Usage: /etc/init.d/truecrypt {start|stop|status}"
	exit 1
esac

exit 0
