#! /usr/bin/env python
import sys,datetime, fileinput, re, getopt


# volem mesurar el % de "slab cache" respecte al total de memoria
# MemTotal:      2097152 kB
# Slab:           310248 kB


def ok_message(value):
	print "SLAB  OK - used ("+value+"%)"
	sys.exit(0)

def warning_message(value):
	print "SLAB  WARNING - used ("+value+"%)"
	sys.exit(1)


def critical_message(value):
	print "SLAB  CRITICAL - used ("+value+"%)"
	sys.exit(2)


def usage():
	print """
Parametres incorrectes
Utilitzacio : ./slab_cache -w percent -c  percent
On,
	-w  Enter entre 0 i 100 en el que salta l'alarma warning
	-c  Enter entre 0 i 100 en el que salta l'alarma critical
	
	El parametre de critical SEMPRE ha de ser mes gran que el de warning
"""

def parse_cmd_line(): 
	warning=0
	critical=0
	
	try:
		options, args = getopt.getopt(sys.argv[1:], 'w:c:')
	except getopt.GetoptError:
	    usage()
	    sys.exit(3)
	
	if len(options) < 1:
		usage(); sys.exit(3)
	
	opts = {}
	try:
		for o, a in options:
			if int(a) > 100:
				usage(); sys.exit(3)
			opts[o] = int(a)
	# en cas que parametre donat no sigui enter, Excepcio
	except ValueError:
		usage(); sys.exit(3)
	if len (opts) < 2 :
		usage(); sys.exit(3)

	warning=opts['-w']
	critical=opts['-c']
	if warning >=critical:
		usage(); sys.exit(3)
	return warning, critical

MEMINFO="/proc/meminfo"
total=0
slab=0

warning=0
critical=0
	
warning,critical = parse_cmd_line()


total_pattern=re.compile("^MemTotal: +(\d{1,50}) kB$")
slab_pattern=re.compile("^Slab: +(\d{1,50}) kB$")

for line in fileinput.input(MEMINFO):
	match=total_pattern.match(line)
	if match!= None:
		total=int(match.group(1))

	match=slab_pattern.match(line)
	if match!= None:
		slab=int(match.group(1))

result = (100*slab)/total

if result < warning:
	ok_message(str(result))	

elif  warning <= result < critical:
	warning_message(str(result))	

else:
	critical_message(str(result))	
